name:                lucid-alpine
version:             0.1.0.7
github:              "MonadicSystems/lucid-alpine"
license:             BSD3
author:              "Monadic Systems LLC"
maintainer:          "tech@monadic.systems"
copyright:           "2022 Monadic Systems LLC"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Use Alpine.js in your lucid templates
category:            Web, HTML

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MonadicSystems/lucid-alpine#readme>

dependencies:
- base >= 4.7 && < 5
- lucid >= 2.11.0
- text

library:
  source-dirs: src

executables:
  lucid-alpine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lucid-alpine

tests:
  lucid-alpine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lucid-alpine
